name: AnglerOnPlot
version: ${project.version}
main: woolyung.angleronplot.AnglerOnPlot
authors: [WooLyung]
description: Fishing Plugin For Mineplanet Server.
website: https://github.com/WooLyung/
commands:
  fish:
    description: fishing command.