message:
  shop:
    no_fish: "§b[Fish] §f판매할 어류가 존재하지 않습니다."
    sell_fish: "§b[Fish] §f%d개의 어류를 판매해 %d 플래닛을 받았습니다."
  fishing:
    caught:
      no_fish: "§b[Fish] §f아무것도 낚이지 않았습니다."
      rill_in_default: "§b[Fish] §f입질이 왔습니다! 방향에 맞춰 마우스를 연타해 릴을 감으세요!"
      rill_in_heavy: "§b[Fish] §f무거운 입질입니다! 방향에 맞춰 마우스를 연타해 릴을 감으세요!"
      rill_in_special: "§b[Fish] §f느낌이 좋은 입질입니다! 방향에 맞춰 마우스를 연타해 릴을 감으세요!"
      miss: "§b[Fish] §f당신은 %s§f을(를) 놓쳤습니다."
      miss_broadcast: "§b[Fish] §f%s님이 %s§f을(를) 놓쳤습니다."
    rill_in:
      success: "§b[Fish] §f당신은 %.2fcm %s§f을(를) 낚았습니다!"
      success_broadcast: "§b[Fish] §f%s님이 %.2fcm %s§f을(를) 낚았습니다!"
      pedia: "§b[Fish] §f당신의 낚시 도감에 %s§f을(를) 기록했습니다."
    fail:
      player: "§b[Fish] §f당신은 %s§f을(를) 낚는 데에 실패했습니다."
      broadcast: "§b[Fish] §f%s님이 %s§f을(를) 낚는 데에 실패했습니다."
  command:
    no_permission: "§b[Fish] §f명령어 권한이 없습니다."
    no_arg: "§b[Fish] §f낚시 명령어를 보려면 /fish help 를 입력하세요."
    wrong_command: "§b[Fish] §f잘못된 명령어입니다."
    pedia:
      wrong_page: "§b[Fish] §f잘못된 페이지입니다."
      small_page: "§b[Fish] §f페이지는 양의 정수여야 합니다."
      no_player: "§b[Fish] §f데이터가 없는 플레이어입니다."
    price:
      error: "§b[Fish] §f가격을 책정할 수 없습니다."
      result: "§b[Fish] §f%s §f의 가격은 %d 플래닛입니다."
  plot:
    not_plot_world: "§b[Fish] §f그 곳은 플롯 월드가 아닙니다."